export const projects = [
  {
    number: '01',
    title: 'PC organization bot',
    description: 'A bot that organizes my PC and connects to Telegram so I can interact with it remotely.',
    status: 'finished',
    stack: 'Python / Telegram Bot API / local automation',
    note: 'The useful part was wiring local actions to a chat interface without making the machine feel like a black box.',
  },
  {
    number: '02',
    title: 'Small Python scripts',
    description: 'Automation, experiments, and tools that solve one annoying problem at a time.',
    status: 'ongoing',
    stack: 'Python / scripting',
    note: 'Small scripts are where I test an idea before giving it a name.',
  },
  {
    number: '03',
    title: 'Unity prototypes',
    description: 'Unfinished game ideas and a brief fight with C#.',
    status: 'paused',
    stack: 'Unity / C#',
    note: 'I failed to finish them, but learned how quickly a project can become too big.',
  },
  {
    number: '04',
    title: 'Text-based RPG',
    description: 'A half-finished RPG with combat based on reflex checks and RNG attacks.',
    status: 'unfinished',
    stack: 'Text interface / game logic / RNG',
    note: 'The interesting problem was making random attacks still feel connected to player timing.',
  },
  {
    number: '05',
    title: 'Koda.py',
    description: 'A local audio LLM powered by Ollama, built to see if I could wire local models together.',
    status: 'prototype',
    stack: 'Python / Ollama / local audio pipeline',
    note: 'A small experiment in keeping the model local and understanding every connection in the chain.',
  },
  {
    number: '06',
    title: 'Endemic lizard analysis',
    description: 'An analysis of endemic lizard species in my country with graphs made using Matplotlib and Pandas.',
    status: 'analysis',
    stack: 'Python / Pandas / Matplotlib',
    note: 'A way to combine one of my animal interests with data cleaning and visualisation.',
  },
  {
    number: '07',
    title: 'NBA prediction model',
    description: 'A linear regression experiment for NBA predictions.',
    status: 'experiment',
    stack: 'Python / Pandas / linear regression',
    note: 'The prediction was not the point. Learning what the data could and could not say was.',
  },
  {
    number: '08',
    title: 'Small web scraper',
    description: 'A scraper that became the key that unlocked my interest in cybersecurity.',
    status: 'completed',
    stack: 'Python / HTTP / parsing',
    note: 'It started as curiosity about collecting data and ended with questions about systems, access, and security.',
  },
]
